// Generated by CoffeeScript 1.9.1
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  angular.module('calendar').controller('CalendarController', function($rootScope, $scope, $modal) {
    return new ((function() {
      function _Class() {
        this.editEvent = bind(this.editEvent, this);
        this.createEvent = bind(this.createEvent, this);
        var event;
        $rootScope.title = "Calendar";
        $scope.uiConfig = {
          calendar: {
            height: 450,
            editable: true,
            header: {
              left: 'month agendaWeek agendaDay',
              center: 'title',
              right: 'today prev,next'
            }
          }
        };
        $scope.createEvent = this.createEvent;
        event = {
          title: 'All Day Event',
          start: new Date(2015, 3, 15)
        };
        $scope.eventSources = [[event]];
      }

      _Class.prototype.createEvent = function() {
        return this.editEvent(null);
      };

      _Class.prototype.editEvent = function(event) {
        var modalInstance;
        modalInstance = $modal.open({
          templateUrl: 'resources/views/modals/event.html',
          controller: 'EventController',
          resolve: {
            event: function() {
              return event;
            }
          }
        });
        return modalInstance.result.then(this.onEventEdited);
      };

      _Class.prototype.onEventEdited = function(event) {
        return $scope.eventSources[0].push(event);
      };

      return _Class;

    })());
  });

}).call(this);

//# sourceMappingURL=CalendarController.js.map
