// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('calendar').controller('EventController', function($scope, $modalInstance, event) {
    return new ((function() {
      function _Class() {
        $scope.event = event;
      }

      return _Class;

    })());
  });

}).call(this);

//# sourceMappingURL=EventController.js.map
