// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('calendar').controller('MapController', function($rootScope, $scope) {
    return new ((function() {
      function _Class() {
        $rootScope.title = "Map";
        $scope.mapOptions = {
          center: new google.maps.LatLng(35.784, -78.670),
          zoom: 15,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
      }

      return _Class;

    })());
  });

}).call(this);

//# sourceMappingURL=MapController.js.map
