// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('calendar').directive('fullHeight', function($timeout) {
    return {
      scope: false,
      link: function($scope, element) {
        var $window, setHeight;
        setHeight = function() {
          return $timeout(function() {
            var height;
            height = $(window).height() - 200;
            return element.css('height', height + 'px');
          });
        };
        $window = angular.element(window);
        $window.on('resize', setHeight());
        $scope.$on('$destroy', function() {
          return $window.off('resize', setHeight());
        });
        return setHeight();
      }
    };
  });

}).call(this);

//# sourceMappingURL=fullHeight.js.map
