// Generated by CoffeeScript 1.9.1
(function() {
  var app;

  app = angular.module('calendar', ['ngRoute', 'ui.bootstrap', 'ui.calendar', 'ui.map']);

  app.config(function($routeProvider) {
    return $routeProvider.when('/home', {
      url: '/'
    }).when('/calendar', {
      templateUrl: '/resources/views/calendar.html',
      controller: 'CalendarController'
    }).when('/map', {
      templateUrl: '/resources/views/map.html',
      controller: 'MapController'
    });
  });

}).call(this);

//# sourceMappingURL=routes.js.map
